export default [
  {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/autumn/01.jpg',
    width: 2,
    height: 3
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/autumn/02.jpeg',
    width: 2,
    height: 3
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/autumn/03.jpeg',
    width: 3,
    height: 2
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/autumn/04.jpeg',
    width: 2,
    height: 3
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/autumn/05.jpeg',
    width: 3,
    height: 2
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/autumn/06.jpeg',
    width: 2,
    height: 3
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/autumn/07.jpeg',
    width: 3,
    height: 2
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/autumn/08.jpg',
    width: 2,
    height: 3
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/autumn/09.jpg',
    width: 2,
    height: 3
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/autumn/10.jpg',
    width: 3,
    height: 2
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/autumn/11.jpg',
    width: 2,
    height: 3
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/autumn/12.jpg',
    width: 3,
    height: 2
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/autumn/13.jpg',
    width: 2,
    height: 3
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/autumn/14.jpg',
    width: 2.5,
    height: 3
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/autumn/15.jpg',
    width: 2.5,
    height: 2
  }
];
