export default [
  {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/everyday/30.jpeg',
    width: 2.5,
    height: 2
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/everyday/29.jpg',
    width: 4.5,
    height: 2
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/everyday/28.jpg',
    width: 2,
    height: 3
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/everyday/27.jpg',
    width: 3,
    height: 2.5
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/everyday/26.jpg',
    width: 3,
    height: 2
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/everyday/25.jpg',
    width: 3,
    height: 2
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/everyday/24.jpg',
    width: 2,
    height: 3
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/everyday/23.jpg',
    width: 3,
    height: 2
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/everyday/22.jpg',
    width: 2.5,
    height: 3
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/everyday/21.jpg',
    width: 3,
    height: 2
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/everyday/20.jpg',
    width: 3,
    height: 2
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/everyday/19.jpg',
    width: 2.5,
    height: 3
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/everyday/18.jpg',
    width: 3,
    height: 2.5
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/everyday/17.jpg',
    width: 3,
    height: 2
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/everyday/16.jpg',
    width: 3,
    height: 2
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/everyday/15.jpg',
    width: 2.5,
    height: 3
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/everyday/14.jpg',
    width: 3,
    height: 2
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/everyday/13.jpg',
    width: 3,
    height: 2
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/everyday/12.jpg',
    width: 3,
    height: 2
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/everyday/11.jpg',
    width: 3,
    height: 2
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/everyday/10.jpg',
    width: 3,
    height: 2
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/everyday/09.jpg',
    width: 2.5,
    height: 3
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/everyday/08.jpeg',
    width: 3,
    height: 2
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/everyday/07.jpeg',
    width: 3, 
    height: 2
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/everyday/06.jpeg',
    width: 3,
    height: 2
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/everyday/05.jpeg',
    width: 3,
    height: 2
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/everyday/04.jpeg',
    width: 2,
    height: 3
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/everyday/03.jpeg',
    width: 3,
    height: 2
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/everyday/02.jpeg',
    width: 2,
    height: 3
  }, {
    src: 'https://s3-us-west-1.amazonaws.com/atsitb-gallery-photos/everyday/01.jpg',
    width: 2,
    height: 3
  }
];
